name: Shell commands

on: [push]

jobs:
  run-shell-command:
    run-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world!"
      - name: multiline script
        run: |
          node -v
          node -v