name: Shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world!"
      - name: multiline script
        run: |
          node -v
          node -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
      - name: Java command
        run: |
          System.out.println("hello from java");
        shell: javas